name: Mirror Bitbucket to GitHub Actions
on: push
env:
    BITBUCKET_USER: ${{ secrets.BITBUCKET_USER }}
    BITBUCKETTOKEN: ${{ secrets.BITBUCKETTOKEN }}
    GITHUB1: ${{ secrets.GITHUB1 }}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to push all branches and tags
      - name: Clone Bitbucket repository
        env:
              BITBUCKET_USER: ${{ secrets.BITBUCKET_USER }}
              BITBUCKETTOKEN: ${{ secrets.BITBUCKETTOKEN }}
        run: |
          git remote remove origin || true
          git clone --mirror https://${{ secrets.BITBUCKET_USER }}:${{ secrets.BITBUCKETTOKEN }}@bitbucket.org/demorepo123/helloworld1.git
          git remote -v
          cd helloworld1.git
      - name: Push to GitHub
        run: |
          cd helloworld1.git
          git remote remove origin || true
          git remote add origin https://x-access-token:${{ secrets.GITHUB1 }}@github.com/redyamsirisha/solid-umbrella.git
          git remote -v  # Print the remote URL to confirm it's correct
          git remote add origin https://x-access-token:${{ secrets.GITHUB1 }}@github.com/redyamsirisha/solid-umbrella.git
          git push --all origin  # Push all branches
          git push --tags origin  # Push all tags
