name: Mirror Bitbucket to GitHub Actions

on:
  push:
    branches:
      - main  # Trigger only when the main branch is pushed

env:
  BITBUCKET_USER: ${{ secrets.BITBUCKET_USER }}
  BITBUCKETTOKEN: ${{ secrets.BITBUCKETTOKEN }}
  GITHUB1: ${{ secrets.GITHUB1 }}

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to fetch all branches and tags

      - name: Clone Bitbucket repository
        env:
          BITBUCKET_USER: ${{ secrets.BITBUCKET_USER }}
          BITBUCKETTOKEN: ${{ secrets.BITBUCKETTOKEN }}
        run: |
          git clone --mirror https://${{ env.BITBUCKET_USER }}:${{ env.BITBUCKETTOKEN }}@bitbucket.org/demorepo123/helloworld1.git
          cd helloworld1.git
          git remote -v

      - name: Push to GitHub (Mirror without Main)
        run: |
          cd helloworld1.git
          git remote add github https://x-access-token:${{ env.GITHUB1 }}@github.com/redyamsirisha/solid-umbrella.git
          git remote -v

          # Push all branches except main
          for branch in $(git for-each-ref --format='%(refname:short)' refs/heads | grep -v 'main'); do
            git push github "$branch:$branch" --force
          done

          # Push all tags
          git push --tags github --force

      - name: Verify Synchronization
        run: |
          cd helloworld1.git
          # Fetch from both remotes
          git fetch origin
          git fetch github

          # Compare branches and tags
          if ! git diff --quiet refs/remotes/origin refs/remotes/github; then
            echo "Repositories are not in sync!"
            exit 1
          else
            echo "Repositories are successfully synchronized!"
          fi

      - name: Cleanup
        run: rm -rf helloworld1.git
